# Generated by Django 5.0.1 on 2024-01-17 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_purchase_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="price",
        ),
    ]
